# Generated by Django 4.2.20 on 2025-08-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rentalcomplaint',
            name='rating',
        ),
    ]
