# Generated by Django 4.2.20 on 2025-08-16 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rentapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_remove_complaint_rating_remove_customuser_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcomplaint',
            name='rental',
        ),
        migrations.AddField(
            model_name='rentalcomplaint',
            name='is_court_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaintdispute',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=rentapp.models.dispute_evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.ImageField(upload_to=rentapp.models.complaint_image_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/def.jpg', null=True, upload_to=rentapp.models.user_avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to=rentapp.models.house_image_upload_path),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='id_document',
            field=models.FileField(upload_to=rentapp.models.user_id_document_upload_path),
        ),
        migrations.AlterField(
            model_name='rentalcomplaint',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rental_complaints', to=settings.AUTH_USER_MODEL, to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='rentalcomplaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=rentapp.models.complaint_evidence_path),
        ),
    ]
