# Generated by Django 4.2.20 on 2025-08-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_remove_rentalcomplaint_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcomplaint',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rental_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
