# Generated by Django 4.2.20 on 2025-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_alter_rentalcomplaint_accused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcomplaint',
            name='court_decision_score',
            field=models.IntegerField(null=True),
        ),
    ]
