# Generated by Django 4.2.20 on 2025-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_usercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintreason',
            options={'ordering': ['type', 'order', 'reason'], 'verbose_name': 'Причина жалобы', 'verbose_name_plural': 'Причины жалоб'},
        ),
        migrations.AddField(
            model_name='complaintreason',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Является ли причина дефолтной'),
        ),
        migrations.AddField(
            model_name='complaintreason',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения'),
        ),
    ]
