# Generated by Django 4.2.20 on 2025-09-13 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_alter_complaintreason_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_register', 'Регистрация пользователя'), ('user_login', 'Вход в систему'), ('user_logout', 'Выход из системы'), ('user_ban', 'Блокировка пользователя'), ('user_unban', 'Разблокировка пользователя'), ('user_verify', 'Верификация пользователя'), ('user_make_admin', 'Назначение администратора'), ('user_remove_admin', 'Снятие прав администратора'), ('complaint_create', 'Создание жалобы'), ('complaint_moderate', 'Модерация жалобы'), ('complaint_resolve', 'Разрешение жалобы'), ('faq_create', 'Создание FAQ'), ('faq_update', 'Обновление FAQ'), ('faq_delete', 'Удаление FAQ'), ('complaint_reason_create', 'Создание причины жалобы'), ('complaint_reason_update', 'Обновление причины жалобы'), ('complaint_reason_delete', 'Удаление причины жалобы'), ('rental_create', 'Создание аренды'), ('rental_confirm', 'Подтверждение аренды'), ('rental_reject', 'Отклонение аренды'), ('comment_create', 'Создание комментария'), ('system_error', 'Системная ошибка')], max_length=50, verbose_name='Тип действия')),
                ('action_description', models.TextField(verbose_name='Описание действия')),
                ('target_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип объекта')),
                ('target_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(verbose_name='Вопрос (RU)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (RU)')),
                ('question_kz', models.TextField(blank=True, null=True, verbose_name='Вопрос (KZ)')),
                ('answer_kz', models.TextField(blank=True, null=True, verbose_name='Ответ (KZ)')),
                ('question_en', models.TextField(blank=True, null=True, verbose_name='Вопрос (EN)')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Ответ (EN)')),
                ('category', models.CharField(choices=[('general', 'Общие вопросы'), ('rental', 'Аренда'), ('complaints', 'Жалобы'), ('verification', 'Верификация'), ('payments', 'Платежи')], default='general', max_length=20)),
                ('user_type', models.CharField(choices=[('both', 'Для всех'), ('tenants', 'Арендаторам'), ('landlords', 'Арендодателям')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['user_type', 'category', 'order', 'question_ru'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='FCM токен')),
                ('device_type', models.CharField(choices=[('web', 'Веб-браузер'), ('android', 'Android'), ('ios', 'iOS'), ('desktop', 'Desktop приложение')], default='web', max_length=20, verbose_name='Тип устройства')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Информация об устройстве')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'FCM токен',
                'verbose_name_plural': 'FCM токены',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email уведомления включены')),
                ('email_complaints', models.BooleanField(default=True, verbose_name='Email о жалобах')),
                ('email_rentals', models.BooleanField(default=True, verbose_name='Email об аренде')),
                ('email_system', models.BooleanField(default=True, verbose_name='Email системные')),
                ('email_promotions', models.BooleanField(default=False, verbose_name='Email промо')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push уведомления включены')),
                ('push_complaints', models.BooleanField(default=True, verbose_name='Push о жалобах')),
                ('push_rentals', models.BooleanField(default=True, verbose_name='Push об аренде')),
                ('push_system', models.BooleanField(default=True, verbose_name='Push системные')),
                ('push_promotions', models.BooleanField(default=False, verbose_name='Push промо')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS уведомления включены')),
                ('sms_urgent_only', models.BooleanField(default=True, verbose_name='SMS только срочные')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Конец тихих часов')),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=50, verbose_name='Часовой пояс')),
                ('digest_frequency', models.CharField(choices=[('none', 'Не отправлять'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='none', max_length=20, verbose_name='Частота дайджеста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.AddField(
            model_name='complaintreason',
            name='reason_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина (EN)'),
        ),
        migrations.AddField(
            model_name='complaintreason',
            name='reason_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина (KZ)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Whether the user is banned'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='Ссылка для действия', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения уведомления', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.house'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.rental'),
        ),
        migrations.AddField(
            model_name='rentalcomplaint',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Комментарий администратора', null=True),
        ),
        migrations.AddField(
            model_name='rentalcomplaint',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='Дата модерации', null=True),
        ),
        migrations.AddField(
            model_name='rentalcomplaint',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Администратор, который модерировал жалобу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('complaint_received', 'Получена жалоба'), ('complaint_status_updated', 'Обновлен статус жалобы'), ('complaint_supported', 'Жалоба поддержана'), ('complaint_commented', 'Новый комментарий к жалобе'), ('rental_confirmed', 'Аренда подтверждена'), ('rental_rejected', 'Аренда отклонена'), ('rental_request_received', 'Получена заявка на аренду'), ('rental_starting_soon', 'Аренда скоро начнется'), ('rental_ending_soon', 'Аренда скоро закончится'), ('user_verified', 'Аккаунт верифицирован'), ('user_banned', 'Аккаунт заблокирован'), ('user_unbanned', 'Аккаунт разблокирован'), ('profile_updated', 'Профиль обновлен'), ('system_maintenance', 'Техническое обслуживание'), ('system_update', 'Обновление системы'), ('security_alert', 'Предупреждение безопасности'), ('new_feature', 'Новая функция'), ('promotion', 'Акция'), ('reminder', 'Напоминание')], default='complaint_received', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='rentapp_not_user_id_9f8069_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='rentapp_not_type_5b7aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='rentapp_not_priorit_374023_idx'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active'], name='rentapp_fcm_user_id_398992_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['device_type'], name='rentapp_fcm_device__ffaf88_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['last_used'], name='rentapp_fcm_last_us_6ee787_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type'], name='rentapp_act_action__a23b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='rentapp_act_user_id_9afd77_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='rentapp_act_created_bf856c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_object_type', 'target_object_id'], name='rentapp_act_target__92fb8b_idx'),
        ),
    ]
