# Generated by Django 4.2.20 on 2025-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0008_activitylog_faq_fcmtoken_notificationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_from_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
