# Generated by Django 4.2.20 on 2025-09-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0009_customuser_birth_date_customuser_is_from_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcomplaint',
            name='court_decision_score',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
