# Generated by Django 4.2.20 on 2025-09-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0010_alter_rentalcomplaint_court_decision_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
